<?php
require_once __DIR__ . '/../../../backend/includes/auth.php';
require_role(['admin','super_admin','inventory_manager']);
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    csrf_verify();$action=$_POST['action']??'';
    try{
        if($action==='save'){
            $id=(int)($_POST['supplier_id']??0);$name=trim((string)($_POST['supplier_name']??''));
            if($name==='')throw new RuntimeException('Supplier name is required.');
            $data=[trim((string)($_POST['contact_person']??''))?:null,trim((string)($_POST['email']??''))?:null,trim((string)($_POST['phone']??''))?:null,trim((string)($_POST['address']??''))?:null,max(0,(int)($_POST['standard_lead_time_days']??7)),max(0,(float)($_POST['minimum_order_value']??0)),($_POST['status']??'active')==='inactive'?'inactive':'active',trim((string)($_POST['notes']??''))?:null];
            if($id>0){$before=$pdo->prepare('SELECT * FROM suppliers WHERE supplier_id=?');$before->execute([$id]);$old=$before->fetch();$stmt=$pdo->prepare('UPDATE suppliers SET supplier_name=?,contact_person=?,email=?,phone=?,address=?,standard_lead_time_days=?,minimum_order_value=?,status=?,notes=? WHERE supplier_id=?');$stmt->execute(array_merge([$name],$data,[$id]));log_activity($pdo,(int)$_SESSION['user_id'],'Updated supplier','Suppliers',$id,$old,array_merge(['supplier_name'=>$name],$data));$message='Supplier updated.';}
            else{$stmt=$pdo->prepare('INSERT INTO suppliers(supplier_name,contact_person,email,phone,address,standard_lead_time_days,minimum_order_value,status,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');$stmt->execute(array_merge([$name],$data,[(int)$_SESSION['user_id']]));$id=(int)$pdo->lastInsertId();log_activity($pdo,(int)$_SESSION['user_id'],'Created supplier','Suppliers',$id);$message='Supplier created.';}
        }elseif($action==='map_product'){
            $supplierId=(int)($_POST['supplier_id']??0);$productId=(int)($_POST['product_id']??0);if(!$supplierId||!$productId)throw new RuntimeException('Supplier and product are required.');
            $preferred=!empty($_POST['is_preferred'])?1:0;if($preferred){$pdo->prepare('UPDATE supplier_products SET is_preferred=0 WHERE product_id=?')->execute([$productId]);}
            $stmt=$pdo->prepare('INSERT INTO supplier_products(supplier_id,product_id,supplier_sku,last_unit_cost,minimum_order_quantity,lead_time_days,is_preferred) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE supplier_sku=VALUES(supplier_sku),last_unit_cost=VALUES(last_unit_cost),minimum_order_quantity=VALUES(minimum_order_quantity),lead_time_days=VALUES(lead_time_days),is_preferred=VALUES(is_preferred)');
            $stmt->execute([$supplierId,$productId,trim((string)($_POST['supplier_sku']??''))?:null,($_POST['last_unit_cost']??'')!==''?(float)$_POST['last_unit_cost']:null,max(1,(int)($_POST['minimum_order_quantity']??1)),max(0,(int)($_POST['lead_time_days']??7)),$preferred]);
            if($preferred){$nameStmt=$pdo->prepare('SELECT supplier_name FROM suppliers WHERE supplier_id=?');$nameStmt->execute([$supplierId]);$name=$nameStmt->fetchColumn();$pdo->prepare('UPDATE products SET preferred_supplier=?,supplier_lead_time_days=? WHERE product_id=?')->execute([$name,max(0,(int)($_POST['lead_time_days']??7)),$productId]);}
            $message='Supplier-product terms saved.';
        }
    }catch(Throwable $e){$error=$e->getMessage();}
}
$suppliers=$pdo->query("SELECT s.*,COUNT(sp.supplier_product_id) product_count FROM suppliers s LEFT JOIN supplier_products sp ON sp.supplier_id=s.supplier_id GROUP BY s.supplier_id ORDER BY s.supplier_name")->fetchAll(PDO::FETCH_ASSOC);
$products=$pdo->query("SELECT product_id,sku,product_name FROM products WHERE status='active' ORDER BY product_name")->fetchAll(PDO::FETCH_ASSOC);
$mappings=$pdo->query("SELECT sp.*,s.supplier_name,p.product_name,p.sku FROM supplier_products sp JOIN suppliers s ON s.supplier_id=sp.supplier_id JOIN products p ON p.product_id=sp.product_id ORDER BY s.supplier_name,p.product_name")->fetchAll(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Suppliers</title><link rel="stylesheet" href="<?= htmlspecialchars(app_url('assets/css/style.css')) ?>"><link rel="stylesheet" href="<?= htmlspecialchars(app_url('assets/css/inventory.css')) ?>"></head><body><div class="app-shell"><?php include __DIR__.'/../sidebar.php';?><main class="main-content"><div class="topbar"><div><h1>Supplier Management</h1><p class="page-subtitle">Maintain contact details, lead times, costs, and product supply terms.</p></div><a class="btn" href="<?= htmlspecialchars(app_url('modules/inventory_management/purchase_orders.php')) ?>">Purchase orders</a></div><?php if($message):?><div class="message success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="message error"><?=htmlspecialchars($error)?></div><?php endif;?>
<div class="two-col"><section class="dashboard-section"><h3>Add supplier</h3><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generate_csrf_token())?>"><input type="hidden" name="action" value="save"><div class="form-grid"><div><label>Supplier name</label><input name="supplier_name" required></div><div><label>Contact person</label><input name="contact_person"></div><div><label>Email</label><input type="email" name="email"></div><div><label>Phone</label><input name="phone"></div><div><label>Lead time (days)</label><input type="number" min="0" name="standard_lead_time_days" value="7"></div><div><label>Minimum order value</label><input type="number" min="0" step="0.01" name="minimum_order_value" value="0"></div></div><label>Address</label><textarea name="address"></textarea><label>Notes</label><textarea name="notes"></textarea><button class="btn">Save supplier</button></form></section>
<section class="dashboard-section"><h3>Map product terms</h3><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generate_csrf_token())?>"><input type="hidden" name="action" value="map_product"><label>Supplier</label><select name="supplier_id" required><option value="">Select</option><?php foreach($suppliers as $s):?><option value="<?=$s['supplier_id']?>"><?=htmlspecialchars($s['supplier_name'])?></option><?php endforeach;?></select><label>Product</label><select name="product_id" required><option value="">Select</option><?php foreach($products as $p):?><option value="<?=$p['product_id']?>"><?=htmlspecialchars($p['product_name'].' ('.$p['sku'].')')?></option><?php endforeach;?></select><div class="form-grid"><div><label>Supplier SKU</label><input name="supplier_sku"></div><div><label>Last unit cost</label><input type="number" min="0" step="0.01" name="last_unit_cost"></div><div><label>MOQ</label><input type="number" min="1" name="minimum_order_quantity" value="1"></div><div><label>Lead time</label><input type="number" min="0" name="lead_time_days" value="7"></div></div><label><input type="checkbox" name="is_preferred" value="1"> Preferred supplier for this product</label><button class="btn">Save terms</button></form></section></div>
<section class="dashboard-section"><h3>Suppliers</h3><div class="table-wrap"><table><tr><th>Name</th><th>Contact</th><th>Lead time</th><th>Products</th><th>Status</th></tr><?php foreach($suppliers as $s):?><tr><td><strong><?=htmlspecialchars($s['supplier_name'])?></strong><br><small><?=htmlspecialchars($s['email']??'')?> <?=htmlspecialchars($s['phone']??'')?></small></td><td><?=htmlspecialchars($s['contact_person']??'-')?></td><td><?=(int)$s['standard_lead_time_days']?> days</td><td><?=(int)$s['product_count']?></td><td><?=htmlspecialchars($s['status'])?></td></tr><?php endforeach;?></table></div></section>
<section class="dashboard-section"><h3>Product supply terms</h3><div class="table-wrap"><table><tr><th>Supplier</th><th>Product</th><th>Cost</th><th>MOQ</th><th>Lead</th><th>Preferred</th></tr><?php foreach($mappings as $m):?><tr><td><?=htmlspecialchars($m['supplier_name'])?></td><td><?=htmlspecialchars($m['product_name'])?><br><small><?=htmlspecialchars($m['sku'])?></small></td><td><?=$m['last_unit_cost']!==null?'₱'.number_format((float)$m['last_unit_cost'],2):'-'?></td><td><?=(int)$m['minimum_order_quantity']?></td><td><?=(int)$m['lead_time_days']?> days</td><td><?=$m['is_preferred']?'Yes':'No'?></td></tr><?php endforeach;?></table></div></section>
</main></div></body></html>
