<?php
// CLI only; the checked-in bundle also supports hosts without a build step.
if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit("CLI only\n");
}

$directory = dirname(__DIR__, 2) . '/frontend/assets/css';
$sources = ['global', 'forms', 'utilities', 'sidebar', 'dashboard', 'tables', 'modals', 'products', 'responsive'];
$bundle = "/* Generated by src/backend/scripts/build_styles.php; edit the source files below. */\n";
foreach ($sources as $source) {
    $css = file_get_contents($directory . '/' . $source . '.css');
    if ($css === false) {
        fwrite(STDERR, "Cannot read stylesheet: {$source}.css\n");
        exit(1);
    }
    $bundle .= "\n/* {$source}.css */\n" . rtrim(str_replace("\r\n", "\n", $css), "\n") . "\n";
}

$target = $directory . '/style.css';
if (in_array('--check', $argv, true)) {
    $current = is_file($target) ? file_get_contents($target) : '';
    if ($current === false || str_replace("\r\n", "\n", $current) !== $bundle) {
        fwrite(STDERR, "Stylesheet bundle is stale. Run php src/backend/scripts/build_styles.php\n");
        exit(1);
    }
    echo "Stylesheet bundle: passed (9 sources, no CSS imports)\n";
} elseif (file_put_contents($target, $bundle) !== strlen($bundle)) {
    fwrite(STDERR, "Could not write stylesheet bundle.\n");
    exit(1);
} else {
    echo "Built style.css from 9 source stylesheets.\n";
}
